{{- range .Values.services }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-%s" $.Release.Name .name }}
spec:
  selector:
    app.kubernetes.io/name: {{ .name }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
  ports:
    - port: {{ .port }}
      targetPort: {{ .port }}
      protocol: TCP
{{- end }}

